[package]
name = "glassdoor-score-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
linked-hash-map = { version = "0.5.6", features = ["serde", "serde_impl"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
